version: '2'
services:
    appgeteway-cassandra:
        container_name: appgeteway-cassandra
        image: cassandra:3.9
        # volumes:
        #     - ~/volumes/jhipster/appgeteway/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    appgeteway-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: appgeteway-cassandra-migration
        links:
            - appgeteway-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
