version: '2'
services:
    lims-elasticsearch:
        container_name: lims-elasticsearch
        image: elasticsearch:2.4.1
        # volumes:
        #     - ~/volumes/jhipster/lims/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
